### ISSUE TITLE
Dictionary for Votes

### ISSUE THREAD

**Issue by devguy97** [tquangsdh20/data-mining#7]
Dictionary for Votes could be changed the position in dictionary due to key's position changing.

**Comment by devguy97** [comment]
The different when changes the values follow the keys
![image](https://user-images.githubusercontent.com/92632730/140460724-11d49382-38eb-4e5e-8c88-c83c1fc93fa7.png)

**Comment by tquangsdh20** [comment]
This issus has been fixed.
